version: '3.9'

services:
  web:
    build: .
    container_name: drf_web
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: drf_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
    depends_on:
      - web

volumes:
  static_volume:
